DEFAULT_CONFIG = {
    "site_url": "https://crm.galaxylabs.online",
    "api_key": "TRACKER_SERVICE_API_KEY",
    "api_secret": "TRACKER_SERVICE_API_SECRET",
    "device_id": "",
    "github_repo": "galaxlabs/windows_tracker_client",
    "github_release_asset": "cclms-tracker-windows-x64.zip",
    "service_name": "CCLMS-Tracker",
    "auto_update_enabled": True,
    "auto_update_check_minutes": 360,
    "offline_queue_db": "tracker_queue.sqlite3",
    "runtime_restart_delay_seconds": 30,
    "productivity_rules": [],
    "device_actions_enabled": False,
    "device_actions_poll_seconds": 60,
    "device_actions_method": "cclms.api.desktop_tracker.get_device_actions",
    "device_action_ack_method": "cclms.api.desktop_tracker.ack_device_action",
    "notifications_enabled": False,
    "notifications_poll_seconds": 60,
    "notifications_method": "cclms.api.desktop_tracker.get_device_notifications",
    "notifications_state_file": "notification_rules.json",
    "map_intelligence_enabled": False,
    "map_cache_db": "scouting_cache.sqlite3",
    "map_sync_scope_seconds": 180,
    "map_context_debounce_seconds": 20,
    "atm_radar_domains": ["atmradar.com"],
    "crm_scouting_domains": ["crm.galaxylabs.online"],
    "maps_domains": ["google.com", "maps.google.com"],
    "browser_relevant_processes": ["chrome.exe", "msedge.exe"],
    "scoped_zip_sync_method": "cclms.api.desktop_tracker.sync_zip_cache_scope",
    "scoped_lead_sync_method": "cclms.api.desktop_tracker.sync_lead_cache_scope",
    "scoped_competitor_sync_method": "cclms.api.desktop_tracker.sync_competitor_cache_scope",
    "location_validate_method": "cclms.api.desktop_tracker.validate_location_scope",
    "competitor_upsert_method": "cclms.api.desktop_tracker.upsert_competitor_kiosk",
    "competitor_keywords": [],
    "duplicate_alert_cooldown_seconds": 600,
    "map_popup_enabled": True,
    "biometric_sync_enabled": False,
    "biometric_sync_interval_minutes": 15,
    "biometric_sync_method": "cclms.api.desktop_tracker.ingest_biometric_attendance",
    "biometric_device": {},
    "heartbeat_seconds": 60,
    "history_seconds": 120,
    "snapshot_min_minutes": 45,
    "snapshot_max_minutes": 75,
    "allowed_browser_processes": ["chrome.exe", "msedge.exe"],
    "call_process_hints": ["ringcentral.exe", "zoiper.exe", "teams.exe", "phone.exe"],
    "verify_ssl": True,
    "log_file": "tracker.log",
}
