DEFAULT_CONFIG = {
    "site_url": "https://crm.galaxylabs.online",
    "api_key": "TRACKER_SERVICE_API_KEY",
    "api_secret": "TRACKER_SERVICE_API_SECRET",
    "device_id": "",
    "github_repo": "galaxlabs/windows_tracker_client",
    "github_release_asset": "cclms-tracker-windows-x64.zip",
    "service_name": "CCLMS-Tracker",
    "auto_update_enabled": True,
    "auto_update_check_minutes": 360,
    "heartbeat_seconds": 60,
    "history_seconds": 120,
    "snapshot_min_minutes": 45,
    "snapshot_max_minutes": 75,
    "allowed_browser_processes": ["chrome.exe", "msedge.exe"],
    "call_process_hints": ["ringcentral.exe", "zoiper.exe", "teams.exe", "phone.exe"],
    "verify_ssl": True,
    "log_file": "tracker.log",
}
