DEFAULT_CONFIG = {
    "site_url": "https://crm.galaxylabs.online",
    "api_key": "TRACKER_SERVICE_API_KEY",
    "api_secret": "TRACKER_SERVICE_API_SECRET",
    "device_id": "",
    "github_repo": "galaxlabs/windows_tracker_client",
    "github_release_asset": "cclms-tracker-windows-x64.zip",
    "service_name": "CCLMS-Tracker",
    "auto_update_enabled": True,
    "auto_update_check_minutes": 360,
    "offline_queue_db": "tracker_queue.sqlite3",
    "runtime_restart_delay_seconds": 30,
    "productivity_rules": [],
    "device_actions_enabled": False,
    "device_actions_poll_seconds": 60,
    "device_actions_method": "cclms.api.desktop_tracker.get_device_actions",
    "device_action_ack_method": "cclms.api.desktop_tracker.ack_device_action",
    "notifications_enabled": False,
    "notifications_poll_seconds": 60,
    "notifications_method": "cclms.api.desktop_tracker.get_device_notifications",
    "notifications_state_file": "notification_rules.json",
    "biometric_sync_enabled": False,
    "biometric_sync_interval_minutes": 15,
    "biometric_sync_method": "cclms.api.desktop_tracker.ingest_biometric_attendance",
    "biometric_device": {},
    "heartbeat_seconds": 60,
    "history_seconds": 120,
    "snapshot_min_minutes": 45,
    "snapshot_max_minutes": 75,
    "allowed_browser_processes": ["chrome.exe", "msedge.exe"],
    "call_process_hints": ["ringcentral.exe", "zoiper.exe", "teams.exe", "phone.exe"],
    "verify_ssl": True,
    "log_file": "tracker.log",
}
